### ISSUE TITLE
管理者コマンドの表示がバグる

### ISSUE THREAD

**Issue by ghost** [poohsan1349/oden-chat#14]
我々が更新したバージョンで"/w-num"を入力すると、バグって表示されます。

**Comment by poohsan1349** [comment]
僕の方で確認したところ，バグっていませんでした…
もう一度確認お願いします．
もし，それでもバグっていた場合はどのようにバグっているのか教えてください．

**Comment by ghost** [comment]
そうでしたか。
一応僕のPCと北村くんのとで症状を確認しているのですが…
文字サイズが異常に小さく表示されて流れていきます。

**Comment by poohsan1349** [comment]
文字サイズのことですか，なるほど．
僕の方でも文字サイズが小さいです！
調べてみますが，仕様かもしれません．

**Comment by poohsan1349** [comment]
/w-num コマンドでも文字サイズが反映できるようにしました．
herokuで確認して下さい．
ソースコードの修正点は
https://github.com/poohsan1349/oden-chat/commit/a8d4c4cfd275c6499dd1a899cd671491d824029e
から確認できます．

**Comment by ghost** [comment]
確認しました、ありがとうございます！
コマンドの送信時に、文字サイズの情報を送信していなかったのが原因なのですね。
